package com.p4.pktgen.enums.registers;

public enum CAM {
	CAM_CTLR_OFFSET,
	CAM_CTLR_SIZE,
	CAM_CTLR_SIZE_IN_WORDS,
	CAM_CTLR_FIELD_ENABLE_SIZE,
	CAM_CTLR_FIELD_ENABLE_OFFSET,
	CAM_CTLR_FIELD_TABLE_SIZE,
	CAM_CTLR_FIELD_TABLE_OFFSET,
	CAM_CTLR_FIELD_BMP_SIZE,
	CAM_CTLR_FIELD_BMP_OFFSET,
	CAM_CTLR_FIELD_MISS_IND_SIZE,
	CAM_CTLR_FIELD_MISS_IND_OFFSET,
	CAM_CTLR_FIELD_SR_EN_SIZE,
	CAM_CTLR_FIELD_SR_EN_OFFSET
}
