package com.p4.pktgen.enums.registers;

public enum Hash {
	HASH_CTLR_OFFSET,
	HASH_CTLR_SIZE,
	HASH_CTLR_SIZE_IN_WORDS,
	HASH_CTLR_ENABLE_SIZE,
	HASH_CTLR_ENABLE_OFFSET,
	HASH_CTLR_TABLE_SIZE,
	HASH_CTLR_TABLE_OFFSET,
	HASH_CTLR_KEY_BMP_SIZE,
	HASH_CTLR_KEY_BMP_OFFSET,
	HASH_CTLR_READ_BMP_SIZE,
	HASH_CTLR_READ_BMP_OFFSET,
	HASH_CTLR_IND_SEG_SIZE,
	HASH_CTLR_IND_SEG_OFFSET,
	HASH_CTLR_ADDR_MASK_SIZE,
	HASH_CTLR_ADDR_MASK_OFFSET,
	HASH_CTLR_MISS_IND_SIZE,
	HASH_CTLR_MISS_IND_OFFSET
}
