package com.p4.pktgen.enums.registers;

public enum Read {
	READ_CTLR_OFFSET,
	READ_CTLR_SIZE,
	READ_CTLR_SIZE_IN_WORDS,
	READ_CTLR_FIELD_ENABLE_SIZE,
	READ_CTLR_FIELD_ENABLE_OFFSET,
	READ_CTLR_FIELD_TABLE_SIZE,
	READ_CTLR_FIELD_TABLE_OFFSET,
	READ_CTLR_FIELD_BMP_SIZE,
	READ_CTLR_FIELD_BMP_OFFSET
}
