package com.p4.pktgen.enums.registers;

public enum TCAMRow {
	TCAM_ROW_CTRL_OFFSET,
	TCAM_ROW_CTRL_SIZE,
	TCAM_ROW_CTRL_SIZE_IN_WORDS,
	TCAM_ROW_CTRL_FIELD_LVL_SEL_SIZE,
	TCAM_ROW_CTRL_FIELD_LVL_SEL_OFFSET,
	TCAM_ROW_CTRL_FIELD_NODE_SEL_SIZE,
	TCAM_ROW_CTRL_FIELD_NODE_SEL_OFFSET,
	TCAM_ROW_CTRL_FIELD_OFFSET_SIZE,
	TCAM_ROW_CTRL_FIELD_OFFSET_OFFSET
}
