package com.p4.pktgen.enums.registers;

public enum TCAMRowAnd {

	TCAM_ROW_CTRL_AND_OFFSET,
	TCAM_ROW_CTRL_AND_SIZE,
	TCAM_ROW_CTRL_AND_SIZE_IN_WORDS,
	TCAM_ROW_CTRL_AND_FIELD_AND_ENABLE_BMP_SIZE,
	TCAM_ROW_CTRL_AND_FIELD_AND_ENABLE_BMP_OFFSET
}
