package com.p4.pktgen.enums.registers;

public enum TCAM {
	TCAM_CTRL_OFFSET,
	TCAM_CTRL_SIZE,
	TCAM_CTRL_SIZE_IN_WORDS,
	TCAM_CTRL_FIELD_ENABLE_SIZE,
	TCAM_CTRL_FIELD_ENABLE_OFFSET,
	TCAM_CTRL_FIELD_TABLE_BMP_SIZE,
	TCAM_CTRL_FIELD_TABLE_BMP_OFFSET,
	TCAM_CTRL_FIELD_KSEG_SIZE,
	TCAM_CTRL_FIELD_KSEG_OFFSET
}
